language: node_js
node_js: '10'
script:
  - npm run build
  - travis_retry npm run travis
os:
  - linux
dist: xenial
cache:
  directories:
    - dist
    - node_modules
env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
  jobs:
    - BROWSER=mac-chrome-latest
    - BROWSER=mac-firefox-latest
    - BROWSER=mac-safari-latest
    - BROWSER=windows-chrome-latest
    - BROWSER=windows-firefox-latest
    - BROWSER=windows-edge-latest
    - BROWSER=ios-latest
    - BROWSER=android-latest
jobs:
  allow_failures:
    - env: BROWSER=android-latest
